### PR TITLE
SHFT-1 make code easier to read with a few loads of comments

### PR DESCRIPTION
**Pull request by foxieze**
Have complete the main files (can be seen on the [Jira issue](https://veryterriblecode.atlassian.net/browse/SHFT-1?atlOrigin=eyJpIjoiZmY3ZWEyYzcxZDlkNDg4Y2I3OTMyNTdhNjljY2IzZGMiLCJwIjoiaiJ9) which files have been completed). A lot of the files here are OpenGL nonsense that I don't understand, so I've left them for someone else to try sort out.

@pipewarp I would appreciate a quick check through to make sure the comments are correct before I merge with main branch.

### CODE REVIEW

**Comment by pipewarp** [comment]
Will take a peep tomorrow! Ill fill out the opengl related things.

**Comment by pipewarp** [comment]
Looks good. I cba to fill out opengl rn so i'll do it later

**Comment by foxieze** [comment]
@pipewarp could you press the review button to fix my OCD saying you haven't reviewed. Files Changed -> Review in top right. Thank youuuuu

**Review by pipewarp — COMMENTED** [review]
drippy :cold_face: :cold_face: :cold_face:

**Pull request merged**
